---
language: objective-c

install: 
 - sudo easy_install cpp-coveralls

script:
 - xctool -project DTCoreText.xcodeproj -scheme DemoApp build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTCoreText.xcodeproj -scheme "DTCoreText (iOS)" test -sdk iphonesimulator
 - xctool -project DTCoreText.xcodeproj -scheme "DTCoreText (Mac)" build test
 - appledoc -o /tmp .

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
